DROP TABLE IF EXISTS animal CASCADE;
DROP TABLE IF EXISTS breed CASCADE;

CREATE TABLE breed (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE animal (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL UNIQUE,
                        age INTEGER NOT NULL CHECK (age > 0),
                        gender ENUM ('FEMALE', 'MALE') NOT NULL,
                        breed_id BIGINT NOT NULL,
                        CONSTRAINT FK5vuppijm6mptl6xm5g9jhegwh FOREIGN KEY (breed_id) REFERENCES breed
);

INSERT INTO breed (id, name) VALUES
                                 (1, 'Afganský chrt'),
                                 (2, 'Americká akita'),
                                 (3, 'Anglický buldog'),
                                 (4, 'Belgický ovčiak'),
                                 (5, 'Bradáč');
